# CC = cc
# CCFLAGS = -Wall -Wextra -Werror
# DEBUG = -g -fsanitize=address

# SRCDIR = srcs/
# OBJDIR = objs

# SRCS = $(SRCDIR)ft_printf_di.c $(SRCDIR)ft_printf_p.c $(SRCDIR)ft_printf_u.c $(SRCDIR)ft_printf_x.c $(SRCDIR)ft_printf_x2.c \
# 		$(SRCDIR)ft_printf.c $(SRCDIR)ft_putchar_fd.c $(SRCDIR)ft_putchar.c $(SRCDIR)ft_putstr_fd.c $(SRCDIR)ft_putstr.c

# OBJS = $(SRCS:$(SRCDIR)%.c=$(OBJDIR)/%.o)

# LIB = libftprintf.a
# TARGET = $(LIB)

# all: $(TARGET)

# debug: $(OBJS)
# 	@echo $(BRIGHT_YELLOW)
# 	$(CC) $(CCFLAGS) $(DEBUG) -o $@ $^
# 	@echo
# 	@echo FSANITIZE=ADDRESS DONE

# $(LIB): $(OBJS)
# 	ar rcs $@ $^

# $(OBJDIR):
# 	@echo $(GREEN)
# 	@mkdir -p $(OBJDIR)

# $(OBJDIR)/%.o: $(SRCDIR)%.c | $(OBJDIR)
# 	$(CC) $(CCFLAGS) -o $@ -c $<

# clean:
# 	@rm -rf $(OBJDIR)
# 	@echo $(BRIGHT_MAGENTA)
# 	@echo ╭━╮╭╮╱╭━╮╭━━╮╭━┳╮╭━┳╮╭━━╮╭━┳╮╭━━╮
# 	@echo ┃╭╯┃┃╱┃┳╯┃╭╮┃┃┃┃┃┃┃┃╰┃┃╯┃┃┃┃┃╭━┫
# 	@echo ┃╰╮┃╰╮┃┻╮┃┣┫┃┃┃┃┃┃┃┃╭┃┃╮┃┃┃┃┃╰╮┃╭╮╭╮╭╮
# 	@echo ╰━╯╰━╯╰━╯╰╯╰╯╰┻━╯╰┻━╯╰━━╯╰┻━╯╰━━╯╰╯╰╯╰╯

# fclean:
# 	@rm -rf $(OBJDIR)
# 	@rm -f $(LIB)
# 	@echo $(RED)╭━━━╮$(BRIGHT_MAGENTA)
# 	@echo $(RED)┃╭━━╯$(BRIGHT_MAGENTA)
# 	@echo $(RED)┃╰━━╮$(BRIGHT_MAGENTA) ╭━╮╭╮╱╭━╮╭━━╮╭━┳╮╭━┳╮╭━━╮╭━┳╮╭━━╮
# 	@echo $(RED)┃╭━━╯$(BRIGHT_MAGENTA) ┃╭╯┃┃╱┃┳╯┃╭╮┃┃┃┃┃┃┃┃┃╰┃┃╯┃┃┃┃┃╭━┫
# 	@echo $(RED)┃┃ $(BRIGHT_MAGENTA) ╱╱┃╰╮┃╰╮┃┻╮┃┣┫┃┃┃┃┃┃┃┃┃┃╭┃┃╮┃┃┃┃┃╰╮┃╭╮╭╮╭╮
# 	@echo $(RED)╰╯ $(BRIGHT_MAGENTA)╱╱ ╰━╯╰━╯╰━╯╰╯╰╯╰┻━╯╰┻━╯╰━━╯╰┻━╯╰━━╯╰╯╰╯╰╯

# re: fclean all

# .PHONY: all clean fclean re

# RESET = "\033[0m"
# BLACK = "\033[30m"
# RED = "\033[31m"
# GREEN = "\033[32m"
# YELLOW = "\033[33m"
# BLUE = "\033[34m"
# MAGENTA = "\033[35m"
# CYAN = "\033[36m"
# WHITE = "\033[37m"
# BRIGHT_BLACK = "\033[90m"
# BRIGHT_RED = "\033[91m"
# BRIGHT_GREEN = "\033[92m"
# BRIGHT_YELLOW = "\033[93m"
# BRIGHT_BLUE = "\033[94m"
# BRIGHT_MAGENTA = "\033[95m"
# BRIGHT_CYAN = "\033[96m"
# BRIGHT_WHITE = "\033[97m"
# BG_RED = "\033[41m"
# BG_GREEN = "\033[42m"
# BG_BLUE = "\033[44m"
# BG_WHITE = "\033[47m"
# BOLD = "\033[1m"
# UNDERLINE = "\033[4m"
# REVERSE = "\033[7m"

# coffee:
# 	@echo ""
# 	@echo "                   ("
# 	@echo "                         )     ("
# 	@echo "               ___...(-------)-....___"
# 	@echo '           .-""       )    (          ""-.'
# 	@echo "      .-''''|-._             )         _.-|"
# 	@echo '     /  .--.|   `""---...........---""`   |'
# 	@echo "    /  /    |                             |"
# 	@echo "    |  |    |                             |"
# 	@echo "     \  \   |                             |"
# 	@echo "      '\ '\ |                             |"
# 	@echo "        '\ '|                             |"
# 	@echo "        _/ /\                             /"
# 	@echo "       (__/  \                           /"
# 	@echo '    _..---""` \                         /`""---.._'
# 	@echo " .-'           \                       /          '-."
# 	@echo ":               '-.__             __.-'              :"
# 	@echo ':                  ) ""---...---"" (                :'
# 	@echo "\'._                '"--...___...--"'              _.'"
# 	@echo '   \""--..__                              __..--""/'
# 	@echo "     '._     """----.....______.....----"""         _.'"
# 	@echo '         ""--..,,_____            _____,,..--"""'
# 	@echo '                      """------"""'
